In [4]:
import pandas as pd
import json

with open("data/raw/track4_test_scores.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print("JSON object type:", type(data))
print("Number of records:", len(data))

JSON object type: <class 'list'>
Number of records: 8000

In [5]:
# Complete Test Scores Dataset Audit

import pandas as pd

# Convert JSON records into DataFrame
test_scores = pd.DataFrame(data)

print("========== BASIC INFORMATION ==========")
print("Rows:", test_scores.shape[0])
print("Columns:", test_scores.shape[1])
print()

print("Column names:")
print(test_scores.columns.tolist())
print()

print("========== DATA TYPES ==========")
print(test_scores.dtypes)
print()

print("========== MISSING VALUES ==========")
print(test_scores.isnull().sum())
print()

print("========== DUPLICATES ==========")
print("Duplicate rows:", test_scores.duplicated().sum())
print()

print("========== FIRST 10 RECORDS ==========")
display(test_scores.head(10))

========== BASIC INFORMATION ==========
Rows: 8000
Columns: 9

Column names:
['assessment_id', 'date', 'school_id', 'grade', 'subject', 'grading_scale', 'avg_score', 'max_marks', 'total_students_assessed']

========== DATA TYPES ==========
assessment_id              object
date                       object
school_id                  object
grade                      object
subject                    object
grading_scale              object
avg_score                  object
max_marks                  object
total_students_assessed     int64
dtype: object

========== MISSING VALUES ==========
assessment_id              0
date                       0
school_id                  0
grade                      0
subject                    0
grading_scale              0
avg_score                  0
max_marks                  0
total_students_assessed    0
dtype: int64

========== DUPLICATES ==========
Duplicate rows: 0

========== FIRST 10 RECORDS ==========

,assessment_id,date,school_id,grade,subject,grading_scale,avg_score,max_marks,total_students_assessed
0,TST005495,2025/05/05,sch0083,8,English,Letter Grade,C,NA,125
1,TST003026,01.07.2025,sch0103,5,Punjabi,pct,63.4%,100,76
2,TST006793,06-Mar-2026,sch_0147,7,Math,CGPA,7.7,10,123
3,TST001798,2025-05-25,SCH0267,5,Science,Percentage,73.0%,100,34
4,TST005946,2026-03-18,SCH0254,6,Ganit,CGPA,4.8,10,148
5,TST004994,2025-07-29,sch0362,7,Punjabi,Letter Grade,A+,NA,113
6,TST002546,15.01.2026,SCH0148,8,Math,CGPA,8.8,10,64
7,TST006290,12.02.2026,SCH-0381,8,Science,Raw Marks,21.6/50,50,109
8,TST001476,2025-06-03,SCH0440,5,Mathematics,pct,43.0%,100,114
9,TST007642,2026-01-11,sch_0597,6,Mathematics,Letter Grade,B,NA,145

In [6]:
# Detailed audit of every column

for col in test_scores.columns:
    print("\n" + "=" * 60)
    print("COLUMN:", col)
    print("Data type:", test_scores[col].dtype)
    print("Missing:", test_scores[col].isna().sum())
    print("Unique values:", test_scores[col].nunique(dropna=False))
    
    print("\nSample values:")
    print(test_scores[col].value_counts(dropna=False).head(20))

============================================================
COLUMN: assessment_id
Data type: object
Missing: 0
Unique values: 8000

Sample values:
assessment_id
TST005495    1
TST003026    1
TST006793    1
TST001798    1
TST005946    1
TST004994    1
TST002546    1
TST006290    1
TST001476    1
TST007642    1
TST003796    1
TST007771    1
TST007892    1
TST002626    1
TST002956    1
TST000891    1
TST006981    1
TST004287    1
TST007479    1
TST001207    1
Name: count, dtype: int64

============================================================
COLUMN: date
Data type: object
Missing: 0
Unique values: 2122

Sample values:
date
2025-06-18     13
2025-06-26     12
2025-12-22     11
2025-08-31     11
2026-02-12     11
2025/09/04     10
07-17-2025     10
2026-03-08     10
29-Aug-2025    10
26/06/2025     10
02.05.2025     10
25.01.2026     10
10-20-2025     10
11.10.2025     10
03.12.2025     10
2025-11-23      9
2025-06-05      9
2025-05-22      9
25-Nov-2025     9
08-25-2025      9
Name: count, dtype: int64

============================================================
COLUMN: school_id
Data type: object
Missing: 0
Unique values: 2800

Sample values:
school_id
SCH0502    14
SCH0154    14
SCH0276    13
SCH0228    13
SCH0082    13
SCH0533    13
SCH0482    13
SCH0557    13
SCH0048    12
SCH0386    12
SCH0319    12
SCH0285    12
SCH0288    11
SCH0173    11
SCH0098    11
SCH0284    11
SCH0594    11
SCH0585    11
SCH0395    11
SCH0392    11
Name: count, dtype: int64

============================================================
COLUMN: grade
Data type: object
Missing: 0
Unique values: 6

Sample values:
grade
8    1412
6    1336
5    1325
7    1316
4    1308
3    1303
Name: count, dtype: int64

============================================================
COLUMN: subject
Data type: object
Missing: 0
Unique values: 8

Sample values:
subject
Hindi          1051
English        1022
Punjabi        1017
Ganit           996
EVS             994
Math            986
Mathematics     972
Science         962
Name: count, dtype: int64

============================================================
COLUMN: grading_scale
Data type: object
Missing: 0
Unique values: 6

Sample values:
grading_scale
Raw Marks       2002
Letter Grade    1983
CGPA            1609
%                816
pct              800
Percentage       790
Name: count, dtype: int64

============================================================
COLUMN: avg_score
Data type: object
Missing: 0
Unique values: 1366

Sample values:
avg_score
C      563
D      550
B      529
E      187
A       79
A+      75
7.7     40
4.2     38
5.8     37
8.8     36
6.0     35
9.4     35
9.1     35
6.6     35
4.5     34
5.5     34
8.0     33
6.5     33
6.7     32
5.2     32
Name: count, dtype: int64

============================================================
COLUMN: max_marks
Data type: object
Missing: 0
Unique values: 5

Sample values:
max_marks
100    3061
NA     1983
10     1609
50      690
25      657
Name: count, dtype: int64

============================================================
COLUMN: total_students_assessed
Data type: int64
Missing: 0
Unique values: 131

Sample values:
total_students_assessed
42     84
106    82
137    79
98     77
73     77
68     76
54     74
80     73
144    73
31     72
60     72
148    72
110    72
83     71
33     70
56     70
138    70
55     70
70     70
141    70
Name: count, dtype: int64

In [7]:
print("Assessment ID examples:")
print(test_scores["assessment_id"].head(20).tolist())

print("\nAssessment ID length:")
print(test_scores["assessment_id"].astype(str).str.len().value_counts())

print("\nIDs not matching TST + 6 digits:")
invalid_ids = test_scores[
    ~test_scores["assessment_id"].astype(str).str.match(r"^TST\d{6}$")
]

print("Invalid IDs:", len(invalid_ids))

if len(invalid_ids) > 0:
    print(invalid_ids["assessment_id"].head(20).tolist())

Assessment ID examples:
['TST005495', 'TST003026', 'TST006793', 'TST001798', 'TST005946', 'TST004994', 'TST002546', 'TST006290', 'TST001476', 'TST007642', 'TST003796', 'TST007771', 'TST007892', 'TST002626', 'TST002956', 'TST000891', 'TST006981', 'TST004287', 'TST007479', 'TST001207']

Assessment ID length:
assessment_id
9    8000
Name: count, dtype: int64

IDs not matching TST + 6 digits:
Invalid IDs: 0

In [8]:
print("Date data type:", test_scores["date"].dtype)
print("Missing values:", test_scores["date"].isna().sum())
print("Unique dates:", test_scores["date"].nunique())

print("\nSample date values:")
print(test_scores["date"].value_counts().head(30))

print("\nDate value lengths:")
print(test_scores["date"].astype(str).str.len().value_counts())

Date data type: object
Missing values: 0
Unique dates: 2122

Sample date values:
date
2025-06-18     13
2025-06-26     12
2025-12-22     11
2025-08-31     11
2026-02-12     11
2025/09/04     10
07-17-2025     10
2026-03-08     10
29-Aug-2025    10
26/06/2025     10
02.05.2025     10
25.01.2026     10
10-20-2025     10
11.10.2025     10
03.12.2025     10
2025-11-23      9
2025-06-05      9
2025-05-22      9
25-Nov-2025     9
08-25-2025      9
2026-01-14      9
29-May-2025     9
19/08/2025      9
01/03/2026      9
01.03.2026      9
2026-03-13      9
04/12/2025      9
26/02/2026      9
2025-10-25      9
2025-05-16      9
Name: count, dtype: int64

Date value lengths:
date
10    6744
11    1256
Name: count, dtype: int64

In [9]:
# Inspect date format patterns

date_series = test_scores["date"].astype(str).str.strip()

print("Total records:", len(date_series))
print()

print("Contains '-':", date_series.str.contains("-").sum())
print("Contains '/':", date_series.str.contains("/").sum())
print("Contains '.':", date_series.str.contains(r"\.", regex=True).sum())

print("\nSample values from each pattern:")

print("\n--- Hyphen (-) ---")
print(date_series[date_series.str.contains("-")].head(15).tolist())

print("\n--- Slash (/) ---")
print(date_series[date_series.str.contains("/")].head(15).tolist())

print("\n--- Dot (.) ---")
print(date_series[date_series.str.contains(r"\.", regex=True)].head(15).tolist())

Total records: 8000

Contains '-': 3983
Contains '/': 2758
Contains '.': 1259

Sample values from each pattern:

--- Hyphen (-) ---
['06-Mar-2026', '2025-05-25', '2026-03-18', '2025-07-29', '2025-06-03', '2026-01-11', '10-Apr-2025', '18-Oct-2025', '2025-07-25', '2026-03-21', '06-11-2025', '11-Dec-2025', '12-27-2025', '2026-02-03', '06-15-2025']

--- Slash (/) ---
['2025/05/05', '04/11/2025', '26/02/2026', '2025/06/30', '12/03/2026', '18/05/2025', '2025/04/29', '2025/04/05', '07/04/2025', '2025/11/15', '2025/09/17', '24/03/2026', '03/08/2025', '2026/02/22', '2025/09/24']

--- Dot (.) ---
['01.07.2025', '15.01.2026', '12.02.2026', '01.06.2025', '24.09.2025', '03.03.2026', '20.01.2026', '27.04.2025', '01.07.2025', '13.11.2025', '23.12.2025', '12.12.2025', '17.11.2025', '29.05.2025', '24.01.2026']

In [10]:
# Find potentially ambiguous numeric dates

date_series = test_scores["date"].astype(str).str.strip()

ambiguous_dates = date_series[
    date_series.str.match(r"^\d{1,2}[-/.]\d{1,2}[-/.]\d{4}$")
].copy()

print("Numeric date records:", len(ambiguous_dates))

print("\nSample numeric dates:")
print(ambiguous_dates.head(30).tolist())

print("\nPotentially ambiguous dates (both first components <= 12):")

def is_ambiguous_date(value):
    parts = value.replace("/", "-").replace(".", "-").split("-")
    
    if len(parts) != 3:
        return False
    
    try:
        first = int(parts[0])
        second = int(parts[1])
        
        # YYYY-MM-DD is not ambiguous
        if len(parts[0]) == 4:
            return False
        
        return first <= 12 and second <= 12
    except:
        return False

ambiguous = ambiguous_dates[ambiguous_dates.apply(is_ambiguous_date)]

print("Ambiguous records:", len(ambiguous))
print(ambiguous.head(50).tolist())

Numeric date records: 3963

Sample numeric dates:
['01.07.2025', '15.01.2026', '12.02.2026', '01.06.2025', '04/11/2025', '26/02/2026', '06-11-2025', '24.09.2025', '12-27-2025', '12/03/2026', '06-15-2025', '03.03.2026', '18/05/2025', '20.01.2026', '09-29-2025', '07-28-2025', '27.04.2025', '07/04/2025', '01.07.2025', '13.11.2025', '24/03/2026', '23.12.2025', '03/08/2025', '12.12.2025', '15/10/2025', '17.11.2025', '19/02/2026', '29.05.2025', '03-08-2026', '07-07-2025']

Potentially ambiguous dates (both first components <= 12):
Ambiguous records: 1534
['01.07.2025', '12.02.2026', '01.06.2025', '04/11/2025', '06-11-2025', '12/03/2026', '03.03.2026', '07/04/2025', '01.07.2025', '03/08/2025', '12.12.2025', '03-08-2026', '07-07-2025', '10.01.2026', '02/11/2025', '04.05.2025', '01/05/2025', '08-04-2025', '07/06/2025', '12.12.2025', '10.12.2025', '12.09.2025', '07/12/2025', '10/04/2025', '08-11-2025', '02/01/2026', '10-02-2025', '09-03-2025', '01.11.2025', '09/07/2025', '11/09/2025', '05.02.2026', '10/12/2025', '06.03.2026', '04/11/2025', '01/11/2025', '06.11.2025', '11/06/2025', '09.07.2025', '10.09.2025', '05/08/2025', '10/02/2026', '09/05/2025', '04-03-2025', '01/05/2025', '10/04/2025', '03-05-2026', '11.08.2025', '10/02/2026', '06/09/2025']

In [11]:
# Inspect unambiguous numeric dates to determine the intended format

date_series = test_scores["date"].astype(str).str.strip()

numeric_dates = date_series[
    date_series.str.match(r"^\d{1,2}[-/.]\d{1,2}[-/.]\d{4}$")
]

def classify_date_format(value):
    parts = value.replace("/", "-").replace(".", "-").split("-")
    
    if len(parts) != 3:
        return "Other"
    
    first, second, year = map(int, parts)
    
    if first > 12 and second <= 12:
        return "DD-MM-YYYY"
    elif second > 12 and first <= 12:
        return "MM-DD-YYYY"
    elif first <= 12 and second <= 12:
        return "Ambiguous"
    else:
        return "Invalid"

format_classification = numeric_dates.apply(classify_date_format)

print(format_classification.value_counts())

print("\n--- Clearly DD-MM-YYYY examples ---")
print(numeric_dates[format_classification == "DD-MM-YYYY"].head(30).tolist())

print("\n--- Clearly MM-DD-YYYY examples ---")
print(numeric_dates[format_classification == "MM-DD-YYYY"].head(30).tolist())

date
DD-MM-YYYY    1702
Ambiguous     1534
MM-DD-YYYY     727
Name: count, dtype: int64

--- Clearly DD-MM-YYYY examples ---
['15.01.2026', '26/02/2026', '24.09.2025', '18/05/2025', '20.01.2026', '27.04.2025', '13.11.2025', '24/03/2026', '23.12.2025', '15/10/2025', '17.11.2025', '19/02/2026', '29.05.2025', '24.01.2026', '27.05.2025', '22.06.2025', '15/01/2026', '30.12.2025', '22/05/2025', '18/07/2025', '26/09/2025', '17.09.2025', '17/01/2026', '24.06.2025', '15/10/2025', '22.12.2025', '24/08/2025', '26/12/2025', '27/09/2025', '28/05/2025']

--- Clearly MM-DD-YYYY examples ---
['12-27-2025', '06-15-2025', '09-29-2025', '07-28-2025', '09-18-2025', '08-25-2025', '02-28-2026', '02-27-2026', '03-14-2026', '01-30-2026', '09-29-2025', '12-17-2025', '10-13-2025', '12-22-2025', '10-21-2025', '09-22-2025', '10-29-2025', '12-15-2025', '11-13-2025', '04-29-2025', '10-20-2025', '11-22-2025', '02-17-2026', '05-17-2025', '04-23-2025', '07-17-2025', '03-25-2026', '05-25-2025', '12-14-2025', '07-28-2025']

In [12]:
import re
from datetime import datetime

def clean_test_date(value):
    value = str(value).strip()

    # YYYY-MM-DD / YYYY/MM/DD / YYYY.MM.DD
    if re.match(r"^\d{4}[-/.]\d{1,2}[-/.]\d{1,2}$", value):
        return pd.to_datetime(value, yearfirst=True, errors="coerce")

    # Text month formats: 06-Mar-2026, 10-Apr-2025, etc.
    if re.match(r"^\d{1,2}-[A-Za-z]{3}-\d{4}$", value):
        return pd.to_datetime(value, format="%d-%b-%Y", errors="coerce")

    # Numeric dates
    parts = re.split(r"[-/.]", value)

    if len(parts) == 3:
        first, second, year = parts

        try:
            first = int(first)
            second = int(second)
            year = int(year)

            # Slash or dot → DD/MM/YYYY
            if "/" in value or "." in value:
                return pd.to_datetime(
                    f"{year}-{second:02d}-{first:02d}",
                    errors="coerce"
                )

            # Hyphen
            if "-" in value:
                # If first > 12 → definitely DD-MM-YYYY
                if first > 12:
                    return pd.to_datetime(
                        f"{year}-{second:02d}-{first:02d}",
                        errors="coerce"
                    )

                # If second > 12 → definitely MM-DD-YYYY
                if second > 12:
                    return pd.to_datetime(
                        f"{year}-{first:02d}-{second:02d}",
                        errors="coerce"
                    )

                # Ambiguous hyphen → use MM-DD-YYYY
                return pd.to_datetime(
                    f"{year}-{first:02d}-{second:02d}",
                    errors="coerce"
                )

        except:
            return pd.NaT

    return pd.NaT


# Create cleaned date column
test_scores["date_clean"] = test_scores["date"].apply(clean_test_date)

print("Original dates:", len(test_scores))
print("Successfully parsed:", test_scores["date_clean"].notna().sum())
print("Invalid/unparsed:", test_scores["date_clean"].isna().sum())

print("\nDate range:")
print("Minimum:", test_scores["date_clean"].min())
print("Maximum:", test_scores["date_clean"].max())

print("\nSample conversion:")
display(test_scores[["date", "date_clean"]].head(30))

Original dates: 8000
Successfully parsed: 8000
Invalid/unparsed: 0

Date range:
Minimum: 2025-04-01 00:00:00
Maximum: 2026-03-31 00:00:00

Sample conversion:

           date date_clean
0    2025/05/05 2025-05-05
1    01.07.2025 2025-07-01
2   06-Mar-2026 2026-03-06
3    2025-05-25 2025-05-25
4    2026-03-18 2026-03-18
5    2025-07-29 2025-07-29
6    15.01.2026 2026-01-15
7    12.02.2026 2026-02-12
8    2025-06-03 2025-06-03
9    2026-01-11 2026-01-11
10   01.06.2025 2025-06-01
11   04/11/2025 2025-11-04
12  10-Apr-2025 2025-04-10
13   26/02/2026 2026-02-26
14  18-Oct-2025 2025-10-18
15   2025-07-25 2025-07-25
16   2026-03-21 2026-03-21
17   2025/06/30 2025-06-30
18   06-11-2025 2025-06-11
19  11-Dec-2025 2025-12-11
20   24.09.2025 2025-09-24
21   12-27-2025 2025-12-27
22   12/03/2026 2026-03-12
23   2026-02-03 2026-02-03
24   06-15-2025 2025-06-15
25   03.03.2026 2026-03-03
26   2025-06-11 2025-06-11
27   2025-11-05 2025-11-05
28   2025-12-09 2025-12-09
29   2025-10-25 2025-10-25

In [13]:
print("=== DATE CLEANING VALIDATION ===")

print("Missing cleaned dates:", test_scores["date_clean"].isna().sum())

print("Dates before 2025-01-01:",
      (test_scores["date_clean"] < "2025-01-01").sum())

print("Dates after 2026-12-31:",
      (test_scores["date_clean"] > "2026-12-31").sum())

print("\nCleaned date data type:")
print(test_scores["date_clean"].dtype)

print("\nSample original → cleaned:")
display(
    test_scores[["date", "date_clean"]]
    .drop_duplicates()
    .head(20)
)

=== DATE CLEANING VALIDATION ===
Missing cleaned dates: 0
Dates before 2025-01-01: 0
Dates after 2026-12-31: 0

Cleaned date data type:
datetime64[ns]

Sample original → cleaned:

           date date_clean
0    2025/05/05 2025-05-05
1    01.07.2025 2025-07-01
2   06-Mar-2026 2026-03-06
3    2025-05-25 2025-05-25
4    2026-03-18 2026-03-18
5    2025-07-29 2025-07-29
6    15.01.2026 2026-01-15
7    12.02.2026 2026-02-12
8    2025-06-03 2025-06-03
9    2026-01-11 2026-01-11
10   01.06.2025 2025-06-01
11   04/11/2025 2025-11-04
12  10-Apr-2025 2025-04-10
13   26/02/2026 2026-02-26
14  18-Oct-2025 2025-10-18
15   2025-07-25 2025-07-25
16   2026-03-21 2026-03-21
17   2025/06/30 2025-06-30
18   06-11-2025 2025-06-11
19  11-Dec-2025 2025-12-11

In [14]:
print("=== SCHOOL ID AUDIT ===")

print("Missing:", test_scores["school_id"].isna().sum())
print("Unique IDs:", test_scores["school_id"].nunique())

print("\nSample school IDs:")
print(test_scores["school_id"].drop_duplicates().head(30).tolist())

print("\nSchool ID value counts:")
print(test_scores["school_id"].value_counts().head(20))

print("\nData type:")
print(test_scores["school_id"].dtype)

=== SCHOOL ID AUDIT ===
Missing: 0
Unique IDs: 2800

Sample school IDs:
['sch0083', 'sch0103', 'sch_0147', 'SCH0267', 'SCH0254', 'sch0362', 'SCH0148', 'SCH-0381', 'SCH0440', 'sch_0597', 'SCH0372', 'sch_0352', 'SCH-0087', 'SCH-0154', '0376', 'SCH0238', 'SCH0268', '0461', 'sch_0427', 'SCH-0439', 'S0524', 'SCH0525', 'sch0214', '0372', 'SCH0551', 'S0096', 'sch0552', 'sch_0496', 'SCH0590', 'SCH0396']

School ID value counts:
school_id
SCH0502    14
SCH0154    14
SCH0276    13
SCH0228    13
SCH0082    13
SCH0533    13
SCH0482    13
SCH0557    13
SCH0048    12
SCH0386    12
SCH0319    12
SCH0285    12
SCH0288    11
SCH0173    11
SCH0098    11
SCH0284    11
SCH0594    11
SCH0585    11
SCH0395    11
SCH0392    11
Name: count, dtype: int64

Data type:
object

In [15]:
print("=== SCHOOL ID FORMAT AUDIT ===")

s = test_scores["school_id"].astype(str).str.strip()

print("Starts with SCH:", s.str.upper().str.startswith("SCH").sum())
print("Starts with S:", s.str.upper().str.startswith("S").sum())
print("Numeric only:", s.str.fullmatch(r"\d+").sum())
print("Contains underscore:", s.str.contains("_", regex=False).sum())
print("Contains hyphen:", s.str.contains("-", regex=False).sum())

print("\nUnique raw formats/examples:")

patterns = {
    "SCH + digits": s.str.fullmatch(r"(?i)SCH\d+"),
    "SCH_ + digits": s.str.fullmatch(r"(?i)SCH_\d+"),
    "SCH- + digits": s.str.fullmatch(r"(?i)SCH-\d+"),
    "S + digits": s.str.fullmatch(r"(?i)S\d+"),
    "Numeric only": s.str.fullmatch(r"\d+")
}

for name, mask in patterns.items():
    print(f"{name}: {mask.sum()}")

print("\nUnusual examples:")
known = pd.Series(False, index=s.index)

for mask in patterns.values():
    known = known | mask

print(s[~known].drop_duplicates().head(30).tolist())

=== SCHOOL ID FORMAT AUDIT ===
Starts with SCH: 6757
Starts with S: 7582
Numeric only: 418
Contains underscore: 1215
Contains hyphen: 1194

Unique raw formats/examples:
SCH + digits: 4348
SCH_ + digits: 1215
SCH- + digits: 1194
S + digits: 825
Numeric only: 418

Unusual examples:
[]

In [16]:
import re

def normalize_school_id(value):
    value = str(value).strip().upper()

    # Extract numeric portion
    numbers = re.findall(r"\d+", value)

    if len(numbers) == 1:
        return f"SCH{int(numbers[0]):04d}"

    return pd.NA

test_scores["school_id_clean"] = (
    test_scores["school_id"]
    .apply(normalize_school_id)
)

print("=== SCHOOL ID CLEANING ===")

print("Original records:", len(test_scores))
print("Missing cleaned IDs:", test_scores["school_id_clean"].isna().sum())
print("Unique raw IDs:", test_scores["school_id"].nunique())
print("Unique cleaned IDs:", test_scores["school_id_clean"].nunique())

print("\nSample original → cleaned:")

display(
    test_scores[["school_id", "school_id_clean"]]
    .drop_duplicates()
    .head(30)
)

=== SCHOOL ID CLEANING ===
Original records: 8000
Missing cleaned IDs: 0
Unique raw IDs: 2800
Unique cleaned IDs: 600

Sample original → cleaned:

   school_id school_id_clean
0    sch0083         SCH0083
1    sch0103         SCH0103
2   sch_0147         SCH0147
3    SCH0267         SCH0267
4    SCH0254         SCH0254
5    sch0362         SCH0362
6    SCH0148         SCH0148
7   SCH-0381         SCH0381
8    SCH0440         SCH0440
9   sch_0597         SCH0597
10   SCH0372         SCH0372
11  sch_0352         SCH0352
12  SCH-0087         SCH0087
13  SCH-0154         SCH0154
14      0376         SCH0376
15   SCH0238         SCH0238
16   SCH0268         SCH0268
17      0461         SCH0461
18  sch_0427         SCH0427
19  SCH-0439         SCH0439
20     S0524         SCH0524
21   SCH0525         SCH0525
22   sch0214         SCH0214
23      0372         SCH0372
24   SCH0551         SCH0551
25     S0096         SCH0096
26   sch0552         SCH0552
27  sch_0496         SCH0496
28   SCH0590         SCH0590
29   SCH0396         SCH0396

In [17]:
# Load cleaned School Master
school_master = pd.read_csv(
    "data/cleaned/school_master_cleaned.csv"
)

master_ids = set(school_master["school_id"].astype(str).str.strip().str.upper())

test_ids = set(
    test_scores["school_id_clean"]
    .dropna()
    .astype(str)
    .str.strip()
    .str.upper()
)

unmatched_ids = test_ids - master_ids

print("=== SCHOOL ID CROSS-DATASET VALIDATION ===")

print("Unique Test Score school IDs:", len(test_ids))
print("Unique School Master IDs:", len(master_ids))
print("Matched IDs:", len(test_ids & master_ids))
print("Unmatched IDs:", len(unmatched_ids))

print("\nUnmatched examples:")
print(sorted(unmatched_ids)[:20])

=== SCHOOL ID CROSS-DATASET VALIDATION ===
Unique Test Score school IDs: 600
Unique School Master IDs: 600
Matched IDs: 600
Unmatched IDs: 0

Unmatched examples:
[]

In [18]:
print("=== GRADE AUDIT ===")

print("Missing:", test_scores["grade"].isna().sum())
print("Unique values:", test_scores["grade"].nunique())

print("\nAll grade values:")
print(sorted(test_scores["grade"].astype(str).unique()))

print("\nValue counts:")
print(test_scores["grade"].value_counts().sort_index())

print("\nData type:")
print(test_scores["grade"].dtype)

=== GRADE AUDIT ===
Missing: 0
Unique values: 6

All grade values:
['3', '4', '5', '6', '7', '8']

Value counts:
grade
3    1303
4    1308
5    1325
6    1336
7    1316
8    1412
Name: count, dtype: int64

Data type:
object

In [19]:
test_scores["grade_clean"] = pd.to_numeric(
    test_scores["grade"],
    errors="coerce"
).astype("Int64")

print("=== GRADE CLEANING VALIDATION ===")

print("Missing cleaned grades:",
      test_scores["grade_clean"].isna().sum())

print("Invalid grades:",
      (~test_scores["grade_clean"].between(3, 8)).sum())

print("Unique cleaned grades:",
      sorted(test_scores["grade_clean"].dropna().unique()))

print("\nData type:")
print(test_scores["grade_clean"].dtype)

print("\nOriginal → cleaned:")
display(
    test_scores[["grade", "grade_clean"]]
    .drop_duplicates()
    .sort_values("grade")
)

=== GRADE CLEANING VALIDATION ===
Missing cleaned grades: 0
Invalid grades: 0
Unique cleaned grades: [np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

Data type:
Int64

Original → cleaned:

   grade  grade_clean
18     3            3
14     4            4
1      5            5
4      6            6
2      7            7
0      8            8

In [20]:
print("=== SUBJECT AUDIT ===")

print("Missing:", test_scores["subject"].isna().sum())
print("Unique subjects:", test_scores["subject"].nunique())

print("\nAll subject values:")
print(test_scores["subject"].drop_duplicates().tolist())

print("\nValue counts:")
print(test_scores["subject"].value_counts())

print("\nData type:")
print(test_scores["subject"].dtype)

=== SUBJECT AUDIT ===
Missing: 0
Unique subjects: 8

All subject values:
['English', 'Punjabi', 'Math', 'Science', 'Ganit', 'Mathematics', 'Hindi', 'EVS']

Value counts:
subject
Hindi          1051
English        1022
Punjabi        1017
Ganit           996
EVS             994
Math            986
Mathematics     972
Science         962
Name: count, dtype: int64

Data type:
object

In [21]:
subject_mapping = {
    "Math": "Mathematics",
    "Ganit": "Mathematics"
}

test_scores["subject_clean"] = (
    test_scores["subject"]
    .astype(str)
    .str.strip()
    .replace(subject_mapping)
)

print("=== SUBJECT CLEANING VALIDATION ===")

print("Missing cleaned subjects:",
      test_scores["subject_clean"].isna().sum())

print("Unique cleaned subjects:",
      test_scores["subject_clean"].nunique())

print("\nCleaned subject values:")
print(sorted(test_scores["subject_clean"].unique()))

print("\nCleaned value counts:")
print(test_scores["subject_clean"].value_counts())

print("\nOriginal → cleaned:")
display(
    test_scores[["subject", "subject_clean"]]
    .drop_duplicates()
    .sort_values(["subject", "subject_clean"])
)

=== SUBJECT CLEANING VALIDATION ===
Missing cleaned subjects: 0
Unique cleaned subjects: 6

Cleaned subject values:
['EVS', 'English', 'Hindi', 'Mathematics', 'Punjabi', 'Science']

Cleaned value counts:
subject_clean
Mathematics    2954
Hindi          1051
English        1022
Punjabi        1017
EVS             994
Science         962
Name: count, dtype: int64

Original → cleaned:

        subject subject_clean
11          EVS           EVS
0       English       English
4         Ganit   Mathematics
10        Hindi         Hindi
2          Math   Mathematics
8   Mathematics   Mathematics
1       Punjabi       Punjabi
3       Science       Science

In [22]:
print("=== GRADING SCALE AUDIT ===")

print("Missing:", test_scores["grading_scale"].isna().sum())
print("Unique grading scales:", test_scores["grading_scale"].nunique())

print("\nAll grading scale values:")
print(test_scores["grading_scale"].drop_duplicates().tolist())

print("\nValue counts:")
print(test_scores["grading_scale"].value_counts())

print("\nData type:")
print(test_scores["grading_scale"].dtype)

print("\nSample grading scale + score + max marks:")
display(
    test_scores[
        ["grading_scale", "avg_score", "max_marks"]
    ].drop_duplicates().head(30)
)

=== GRADING SCALE AUDIT ===
Missing: 0
Unique grading scales: 6

All grading scale values:
['Letter Grade', 'pct', 'CGPA', 'Percentage', 'Raw Marks', '%']

Value counts:
grading_scale
Raw Marks       2002
Letter Grade    1983
CGPA            1609
%                816
pct              800
Percentage       790
Name: count, dtype: int64

Data type:
object

Sample grading scale + score + max marks:

   grading_scale avg_score max_marks
0   Letter Grade         C        NA
1            pct     63.4%       100
2           CGPA       7.7        10
3     Percentage     73.0%       100
4           CGPA       4.8        10
5   Letter Grade        A+        NA
6           CGPA       8.8        10
7      Raw Marks   21.6/50        50
8            pct     43.0%       100
9   Letter Grade         B        NA
10          CGPA       8.5        10
11  Letter Grade         D        NA
12          CGPA       8.9        10
13           pct     85.8%       100
14           pct     76.7%       100
15    Percentage     55.6%       100
16          CGPA       7.9        10
17     Raw Marks   40.1/50        50
18     Raw Marks   16.0/25        25
22           pct     84.7%       100
24          CGPA       6.2        10
25             %     89.3%       100
26          CGPA       4.6        10
30    Percentage     63.3%       100
33          CGPA       5.1        10
35           pct     41.9%       100
36  Letter Grade         A        NA
37    Percentage     61.8%       100
39           pct     48.2%       100
40             %     55.8%       100

In [23]:
grading_scale_mapping = {
    "pct": "Percentage",
    "%": "Percentage",
    "Percentage": "Percentage",
    "Letter Grade": "Letter Grade",
    "Raw Marks": "Raw Marks",
    "CGPA": "CGPA"
}

test_scores["grading_scale_clean"] = (
    test_scores["grading_scale"]
    .astype(str)
    .str.strip()
    .replace(grading_scale_mapping)
)

print("=== GRADING SCALE STANDARDIZATION ===")

print("Missing cleaned scales:",
      test_scores["grading_scale_clean"].isna().sum())

print("Unique cleaned scales:",
      test_scores["grading_scale_clean"].nunique())

print("\nCleaned grading scales:")
print(test_scores["grading_scale_clean"].value_counts())

print("\nOriginal → cleaned:")
display(
    test_scores[["grading_scale", "grading_scale_clean"]]
    .drop_duplicates()
    .sort_values(["grading_scale", "grading_scale_clean"])
)

=== GRADING SCALE STANDARDIZATION ===
Missing cleaned scales: 0
Unique cleaned scales: 4

Cleaned grading scales:
grading_scale_clean
Percentage      2406
Raw Marks       2002
Letter Grade    1983
CGPA            1609
Name: count, dtype: int64

Original → cleaned:

   grading_scale grading_scale_clean
25             %          Percentage
2           CGPA                CGPA
0   Letter Grade        Letter Grade
3     Percentage          Percentage
7      Raw Marks           Raw Marks
1            pct          Percentage

In [24]:
print("=== AVG SCORE AUDIT BY GRADING SCALE ===")

for scale in test_scores["grading_scale_clean"].unique():
    subset = test_scores[
        test_scores["grading_scale_clean"] == scale
    ]["avg_score"]

    print(f"\n--- {scale} ---")
    print("Records:", len(subset))
    print("Missing:", subset.isna().sum())
    print("Data type:", subset.dtype)
    print("Unique values:", subset.nunique())
    print("Examples:")
    print(subset.drop_duplicates().head(20).tolist())

=== AVG SCORE AUDIT BY GRADING SCALE ===

--- Letter Grade ---
Records: 1983
Missing: 0
Data type: object
Unique values: 6
Examples:
['C', 'A+', 'B', 'D', 'A', 'E']

--- Percentage ---
Records: 2406
Missing: 0
Data type: object
Unique values: 542
Examples:
['63.4%', '73.0%', '43.0%', '85.8%', '76.7%', '55.6%', '84.7%', '89.3%', '63.3%', '41.9%', '61.8%', '48.2%', '55.8%', '82.2%', '92.4%', '66.3%', '87.5%', '44.4%', '41.0%', '46.3%']

--- CGPA ---
Records: 1609
Missing: 0
Data type: object
Unique values: 56
Examples:
['7.7', '4.8', '8.8', '8.5', '8.9', '7.9', '6.2', '4.6', '5.1', '7.3', '5.2', '4.7', '7.4', '5.3', '8.3', '9.0', '4.5', '7.5', '4.4', '5.8']

--- Raw Marks ---
Records: 2002
Missing: 0
Data type: object
Unique values: 762
Examples:
['21.6/50', '40.1/50', '16.0/25', '15.0/25', '45.0/50', '83.1/100', '27.9/50', '12.6/25', '30.6/50', '41.0/100', '14.3/25', '10.9/25', '19.6/25', '10.2/25', '21.1/50', '59.8/100', '54.6/100', '17.6/25', '36.0/50', '20.2/25']

In [25]:
print("=== DETAILED AVG SCORE AUDIT ===")

# Percentage
percentage = test_scores.loc[
    test_scores["grading_scale_clean"] == "Percentage",
    "avg_score"
].astype(str).str.replace("%", "", regex=False)

print("\n--- Percentage ---")
print("Min:", pd.to_numeric(percentage, errors="coerce").min())
print("Max:", pd.to_numeric(percentage, errors="coerce").max())

# CGPA
cgpa = test_scores.loc[
    test_scores["grading_scale_clean"] == "CGPA",
    "avg_score"
]

print("\n--- CGPA ---")
print("Min:", pd.to_numeric(cgpa, errors="coerce").min())
print("Max:", pd.to_numeric(cgpa, errors="coerce").max())

# Letter Grade
letter = test_scores.loc[
    test_scores["grading_scale_clean"] == "Letter Grade",
    "avg_score"
]

print("\n--- Letter Grade ---")
print("Values:", sorted(letter.astype(str).unique()))
print("Counts:")
print(letter.value_counts())

# Raw Marks
raw = test_scores.loc[
    test_scores["grading_scale_clean"] == "Raw Marks",
    "avg_score"
].astype(str)

raw_parts = raw.str.extract(r"^\s*([\d.]+)\s*/\s*([\d.]+)\s*$")

raw_obtained = pd.to_numeric(raw_parts[0], errors="coerce")
raw_max = pd.to_numeric(raw_parts[1], errors="coerce")

print("\n--- Raw Marks ---")
print("Invalid format:", raw_obtained.isna().sum())
print("Obtained min:", raw_obtained.min())
print("Obtained max:", raw_obtained.max())
print("Maximum marks values:", sorted(raw_max.dropna().unique()))

print("\nRaw marks examples:")
print(raw.drop_duplicates().head(20).tolist())

=== DETAILED AVG SCORE AUDIT ===

--- Percentage ---
Min: 40.0
Max: 95.0

--- CGPA ---
Min: 4.0
Max: 9.5

--- Letter Grade ---
Values: ['A', 'A+', 'B', 'C', 'D', 'E']
Counts:
avg_score
C     563
D     550
B     529
E     187
A      79
A+     75
Name: count, dtype: int64

--- Raw Marks ---
Invalid format: 0
Obtained min: 10.0
Obtained max: 94.9
Maximum marks values: [np.int64(25), np.int64(50), np.int64(100)]

Raw marks examples:
['21.6/50', '40.1/50', '16.0/25', '15.0/25', '45.0/50', '83.1/100', '27.9/50', '12.6/25', '30.6/50', '41.0/100', '14.3/25', '10.9/25', '19.6/25', '10.2/25', '21.1/50', '59.8/100', '54.6/100', '17.6/25', '36.0/50', '20.2/25']

In [26]:
import numpy as np

# Start with an empty numeric column
test_scores["score_percentage"] = np.nan

# 1. Percentage
mask = test_scores["grading_scale_clean"] == "Percentage"

test_scores.loc[mask, "score_percentage"] = (
    test_scores.loc[mask, "avg_score"]
    .astype(str)
    .str.replace("%", "", regex=False)
    .str.strip()
    .astype(float)
)

# 2. CGPA → Percentage
mask = test_scores["grading_scale_clean"] == "CGPA"

test_scores.loc[mask, "score_percentage"] = (
    pd.to_numeric(
        test_scores.loc[mask, "avg_score"],
        errors="coerce"
    ) * 10
)

# 3. Letter Grade → Percentage
letter_mapping = {
    "A+": 95,
    "A": 85,
    "B": 75,
    "C": 65,
    "D": 55,
    "E": 40
}

mask = test_scores["grading_scale_clean"] == "Letter Grade"

test_scores.loc[mask, "score_percentage"] = (
    test_scores.loc[mask, "avg_score"]
    .astype(str)
    .str.strip()
    .map(letter_mapping)
)

# 4. Raw Marks → Percentage
mask = test_scores["grading_scale_clean"] == "Raw Marks"

raw_parts = test_scores.loc[mask, "avg_score"].astype(str).str.extract(
    r"^\s*([\d.]+)\s*/\s*([\d.]+)\s*$"
)

obtained = pd.to_numeric(raw_parts[0], errors="coerce")
maximum = pd.to_numeric(raw_parts[1], errors="coerce")

test_scores.loc[mask, "score_percentage"] = (
    obtained / maximum * 100
)

print("=== SCORE PERCENTAGE CONVERSION ===")

print("Missing converted scores:",
      test_scores["score_percentage"].isna().sum())

print("Total records:",
      len(test_scores))

print("Minimum:",
      test_scores["score_percentage"].min())

print("Maximum:",
      test_scores["score_percentage"].max())

print("\nAverage score percentage:",
      round(test_scores["score_percentage"].mean(), 2))

print("\nScores by grading scale:")
print(
    test_scores.groupby("grading_scale_clean")["score_percentage"]
    .agg(["count", "min", "max", "mean"])
)

print("\nSample converted values:")
display(
    test_scores[
        ["grading_scale_clean", "avg_score", "score_percentage"]
    ].sample(20, random_state=42)
)

=== SCORE PERCENTAGE CONVERSION ===
Missing converted scores: 0
Total records: 8000
Minimum: 40.0
Maximum: 95.0

Average score percentage: 66.62

Scores by grading scale:
                     count   min   max       mean
grading_scale_clean
CGPA                  1609  40.0  95.0  67.172157
Letter Grade          1983  40.0  95.0  64.467978
Percentage            2406  40.0  95.0  67.275145
Raw Marks             2002  40.0  95.0  67.530719

Sample converted values:

     grading_scale_clean avg_score  score_percentage
2215        Letter Grade         D              55.0
2582          Percentage     91.1%              91.1
1662           Raw Marks  72.2/100              72.2
3027                CGPA       7.0              70.0
4343        Letter Grade         B              75.0
2680          Percentage     82.8%              82.8
1765        Letter Grade         D              55.0
1123          Percentage     79.2%              79.2
4054        Letter Grade         D              55.0
3761        Letter Grade         D              55.0
1535                CGPA       8.3              83.0
2944        Letter Grade         B              75.0
2987        Letter Grade         C              65.0
4291          Percentage     41.1%              41.1
4342          Percentage     48.6%              48.6
4424        Letter Grade         B              75.0
7941        Letter Grade         B              75.0
4997        Letter Grade         D              55.0
2748          Percentage     70.5%              70.5
2302           Raw Marks  59.3/100              59.3

In [27]:
print("=== SCORE CONVERSION SPOT CHECK ===")

for scale in ["Percentage", "CGPA", "Letter Grade", "Raw Marks"]:
    print(f"\n--- {scale} ---")

    display(
        test_scores[
            test_scores["grading_scale_clean"] == scale
        ][
            ["avg_score", "score_percentage"]
        ].drop_duplicates().head(5)
    )

=== SCORE CONVERSION SPOT CHECK ===

--- Percentage ---

   avg_score  score_percentage
1      63.4%              63.4
3      73.0%              73.0
8      43.0%              43.0
13     85.8%              85.8
14     76.7%              76.7

--- CGPA ---

   avg_score  score_percentage
2        7.7              77.0
4        4.8              48.0
6        8.8              88.0
10       8.5              85.0
12       8.9              89.0

--- Letter Grade ---

   avg_score  score_percentage
0          C              65.0
5         A+              95.0
9          B              75.0
11         D              55.0
36         A              85.0

--- Raw Marks ---

   avg_score  score_percentage
7    21.6/50              43.2
17   40.1/50              80.2
18   16.0/25              64.0
45   15.0/25              60.0
50   45.0/50              90.0

In [29]:
print("=== MAX MARKS DETAILED AUDIT ===")

print("Missing (Pandas NA):",
      test_scores["max_marks"].isna().sum())

print("String 'NA' values:",
      (test_scores["max_marks"].astype(str).str.strip().str.upper() == "NA").sum())

print("\nValue counts:")
print(
    test_scores["max_marks"]
    .astype(str)
    .str.strip()
    .value_counts()
)

print("\nData type:")
print(test_scores["max_marks"].dtype)

=== MAX MARKS DETAILED AUDIT ===
Missing (Pandas NA): 0
String 'NA' values: 1983

Value counts:
max_marks
100    3061
NA     1983
10     1609
50      690
25      657
Name: count, dtype: int64

Data type:
object

In [30]:
print("=== MAX MARKS vs GRADING SCALE ===")

check = pd.crosstab(
    test_scores["grading_scale_clean"],
    test_scores["max_marks"].astype(str).str.strip()
)

print(check)

=== MAX MARKS vs GRADING SCALE ===
max_marks              10   100   25   50    NA
grading_scale_clean
CGPA                 1609     0    0    0     0
Letter Grade            0     0    0    0  1983
Percentage              0  2406    0    0     0
Raw Marks               0   655  657  690     0

In [31]:
test_scores["max_marks_clean"] = pd.to_numeric(
    test_scores["max_marks"].replace(
        {"NA": np.nan, "na": np.nan}
    ),
    errors="coerce"
)

print("=== MAX MARKS CLEANING VALIDATION ===")

print("Total records:", len(test_scores))

print("Missing after cleaning:",
      test_scores["max_marks_clean"].isna().sum())

print("Non-missing after cleaning:",
      test_scores["max_marks_clean"].notna().sum())

print("\nUnique cleaned values:")
print(
    sorted(
        test_scores["max_marks_clean"]
        .dropna()
        .unique()
    )
)

print("\nData type:")
print(test_scores["max_marks_clean"].dtype)

print("\nMissing by grading scale:")
print(
    test_scores.groupby("grading_scale_clean")["max_marks_clean"]
    .apply(lambda x: x.isna().sum())
)

=== MAX MARKS CLEANING VALIDATION ===
Total records: 8000
Missing after cleaning: 1983
Non-missing after cleaning: 6017

Unique cleaned values:
[np.float64(10.0), np.float64(25.0), np.float64(50.0), np.float64(100.0)]

Data type:
float64

Missing by grading scale:
grading_scale_clean
CGPA               0
Letter Grade    1983
Percentage         0
Raw Marks          0
Name: max_marks_clean, dtype: int64

C:\Users\chinm\AppData\Local\Temp\ipykernel_11696\876432376.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_scores["max_marks"].replace(

In [32]:
print("=== TOTAL STUDENTS ASSESSED AUDIT ===")

print("Missing:",
      test_scores["total_students_assessed"].isna().sum())

print("Unique values:",
      test_scores["total_students_assessed"].nunique())

print("Minimum:",
      test_scores["total_students_assessed"].min())

print("Maximum:",
      test_scores["total_students_assessed"].max())

print("\nNegative values:",
      (test_scores["total_students_assessed"] < 0).sum())

print("Zero values:",
      (test_scores["total_students_assessed"] == 0).sum())

print("\nData type:")
print(test_scores["total_students_assessed"].dtype)

print("\nSample values:")
print(
    test_scores["total_students_assessed"]
    .value_counts()
    .sort_index()
    .head(30)
)

=== TOTAL STUDENTS ASSESSED AUDIT ===
Missing: 0
Unique values: 131
Minimum: 20
Maximum: 150

Negative values: 0
Zero values: 0

Data type:
int64

Sample values:
total_students_assessed
20    63
21    48
22    60
23    64
24    59
25    61
26    65
27    65
28    56
29    40
30    51
31    72
32    60
33    70
34    58
35    61
36    61
37    67
38    39
39    57
40    56
41    59
42    84
43    63
44    49
45    57
46    58
47    61
48    57
49    51
Name: count, dtype: int64

In [33]:
test_scores["total_students_assessed_clean"] = pd.to_numeric(
    test_scores["total_students_assessed"],
    errors="coerce"
).astype("Int64")

print("=== TOTAL STUDENTS ASSESSED VALIDATION ===")

print("Missing cleaned values:",
      test_scores["total_students_assessed_clean"].isna().sum())

print("Values <= 0:",
      (test_scores["total_students_assessed_clean"] <= 0).sum())

print("Values > 150:",
      (test_scores["total_students_assessed_clean"] > 150).sum())

print("Minimum:",
      test_scores["total_students_assessed_clean"].min())

print("Maximum:",
      test_scores["total_students_assessed_clean"].max())

print("\nData type:")
print(test_scores["total_students_assessed_clean"].dtype)

=== TOTAL STUDENTS ASSESSED VALIDATION ===
Missing cleaned values: 0
Values <= 0: 0
Values > 150: 0
Minimum: 20
Maximum: 150

Data type:
Int64

In [34]:
print("==========================================")
print("FINAL TEST SCORES DATASET VALIDATION")
print("==========================================")

print("\nShape:")
print(test_scores.shape)

print("\nDuplicate rows:")
print(test_scores.duplicated().sum())

print("\nMissing values:")
print(test_scores.isna().sum())

print("\nCleaned score range:")
print(
    test_scores["score_percentage"].min(),
    "to",
    test_scores["score_percentage"].max()
)

print("\nInvalid score percentages:")
print(
    (
        (test_scores["score_percentage"] < 0) |
        (test_scores["score_percentage"] > 100)
    ).sum()
)

print("\nUnique schools:")
print(test_scores["school_id_clean"].nunique())

print("\nUnique grades:")
print(sorted(test_scores["grade_clean"].unique()))

print("\nUnique subjects:")
print(sorted(test_scores["subject_clean"].unique()))

print("\nUnique grading scales:")
print(sorted(test_scores["grading_scale_clean"].unique()))

print("\nDate range:")
print(
    test_scores["date_clean"].min(),
    "to",
    test_scores["date_clean"].max()
)

print("\nTotal students assessed range:")
print(
    test_scores["total_students_assessed_clean"].min(),
    "to",
    test_scores["total_students_assessed_clean"].max()
)

==========================================
FINAL TEST SCORES DATASET VALIDATION
==========================================

Shape:
(8000, 17)

Duplicate rows:
0

Missing values:
assessment_id                       0
date                                0
school_id                           0
grade                               0
subject                             0
grading_scale                       0
avg_score                           0
max_marks                           0
total_students_assessed             0
date_clean                          0
school_id_clean                     0
grade_clean                         0
subject_clean                       0
grading_scale_clean                 0
score_percentage                    0
max_marks_clean                  1983
total_students_assessed_clean       0
dtype: int64

Cleaned score range:
40.0 to 95.0

Invalid score percentages:
0

Unique schools:
600

Unique grades:
[np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

Unique subjects:
['EVS', 'English', 'Hindi', 'Mathematics', 'Punjabi', 'Science']

Unique grading scales:
['CGPA', 'Letter Grade', 'Percentage', 'Raw Marks']

Date range:
2025-04-01 00:00:00 to 2026-03-31 00:00:00

Total students assessed range:
20 to 150

In [35]:
# Select final analysis-ready columns
test_scores_cleaned = test_scores[
    [
        "assessment_id",
        "date_clean",
        "school_id_clean",
        "grade_clean",
        "subject_clean",
        "grading_scale_clean",
        "score_percentage",
        "max_marks_clean",
        "total_students_assessed_clean"
    ]
].copy()

# Rename columns to clean final names
test_scores_cleaned.columns = [
    "assessment_id",
    "date",
    "school_id",
    "grade",
    "subject",
    "grading_scale",
    "score_percentage",
    "max_marks",
    "total_students_assessed"
]

# Save
output_path = "data/cleaned/test_scores_cleaned.csv"

test_scores_cleaned.to_csv(
    output_path,
    index=False
)

print("=== FILE SAVED ===")
print("Path:", output_path)
print("Shape:", test_scores_cleaned.shape)

print("\nColumns:")
print(test_scores_cleaned.columns.tolist())

print("\nMissing values:")
print(test_scores_cleaned.isna().sum())

print("\nDuplicate rows:")
print(test_scores_cleaned.duplicated().sum())

=== FILE SAVED ===
Path: data/cleaned/test_scores_cleaned.csv
Shape: (8000, 9)

Columns:
['assessment_id', 'date', 'school_id', 'grade', 'subject', 'grading_scale', 'score_percentage', 'max_marks', 'total_students_assessed']

Missing values:
assessment_id                 0
date                          0
school_id                     0
grade                         0
subject                       0
grading_scale                 0
score_percentage              0
max_marks                  1983
total_students_assessed       0
dtype: int64

Duplicate rows:
0

In [36]:
print("=== TEST SCORES CLEANING PROOF ===")

print("RAW DATA")
print("Rows:", 8000)
print("Columns:", 9)

print("\nCLEANED DATA")
print("Rows:", len(test_scores_cleaned))
print("Columns:", len(test_scores_cleaned.columns))

print("\nDATA QUALITY")
print("Duplicate rows:", test_scores_cleaned.duplicated().sum())
print("Missing assessment IDs:", test_scores_cleaned["assessment_id"].isna().sum())
print("Missing dates:", test_scores_cleaned["date"].isna().sum())
print("Missing school IDs:", test_scores_cleaned["school_id"].isna().sum())
print("Missing grades:", test_scores_cleaned["grade"].isna().sum())
print("Missing subjects:", test_scores_cleaned["subject"].isna().sum())
print("Missing scores:", test_scores_cleaned["score_percentage"].isna().sum())
print("Missing max marks:", test_scores_cleaned["max_marks"].isna().sum())
print("Missing students assessed:",
      test_scores_cleaned["total_students_assessed"].isna().sum())

=== TEST SCORES CLEANING PROOF ===
RAW DATA
Rows: 8000
Columns: 9

CLEANED DATA
Rows: 8000
Columns: 9

DATA QUALITY
Duplicate rows: 0
Missing assessment IDs: 0
Missing dates: 0
Missing school IDs: 0
Missing grades: 0
Missing subjects: 0
Missing scores: 0
Missing max marks: 1983
Missing students assessed: 0